/**
 * Mock data for demo mode when backend is not running
 */
import type { Service, Category, ProviderDashboard, ConsumerDashboard, Review, Transaction } from "@/types";

export const mockCategories: Category[] = [
  { id: "1", name: "Chat", slug: "chat", description: "Conversational AI", icon: "💬", color: "#00D1FF" },
  { id: "2", name: "OCR", slug: "ocr", description: "Optical Character Recognition", icon: "📄", color: "#FF6B6B" },
  { id: "3", name: "Vision", slug: "vision", description: "Computer vision", icon: "👁️", color: "#A855F7" },
  { id: "4", name: "Speech-to-Text", slug: "speech-to-text", description: "Audio transcription", icon: "🎤", color: "#F59E0B" },
  { id: "5", name: "Translation", slug: "translation", description: "Multi-language translation", icon: "🌐", color: "#10B981" },
  { id: "6", name: "Summarization", slug: "summarization", description: "Text summarization", icon: "📝", color: "#3B82F6" },
  { id: "7", name: "Coding", slug: "coding", description: "Code generation", icon: "💻", color: "#8B5CF6" },
  { id: "8", name: "Image Generation", slug: "image-generation", description: "AI image creation", icon: "🎨", color: "#EC4899" },
  { id: "9", name: "Video", slug: "video", description: "Video analysis", icon: "🎬", color: "#EF4444" },
  { id: "10", name: "Audio", slug: "audio", description: "Audio processing", icon: "🔊", color: "#06B6D4" },
  { id: "11", name: "Document AI", slug: "document-ai", description: "Document processing", icon: "📋", color: "#14B8A6" },
];

export const mockServices: Service[] = [
  {
    id: "s1", provider_id: "p1", category_id: "2", name: "DocuScan Pro",
    description: "Enterprise-grade OCR powered by a fine-tuned vision transformer. Supports 50+ languages, handwriting recognition, table extraction, and structured data output.",
    short_description: "Enterprise OCR with 50+ language support",
    price_ada: 2.5, endpoint_url: "https://api.visionai.labs/v2/ocr",
    docs_url: "https://docs.visionai.labs", avg_latency_ms: 1200, success_rate: 99.3,
    total_jobs: 9547, uptime: 99.9, rating: 4.92, review_count: 234,
    version: "2.1.0", model_name: "DocuVision-T5-Large",
    example_input: '{"image_url": "https://example.com/invoice.png", "language": "en"}',
    example_output: '{"text": "Invoice #12345...", "confidence": 0.98}',
    tags: "ocr,document,invoice", status: "active",
    created_at: "2026-03-15T10:00:00Z", updated_at: "2026-07-10T10:00:00Z",
    provider_name: "VisionAI Labs", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "OCR", category_icon: "📄",
  },
  {
    id: "s2", provider_id: "p2", category_id: "1", name: "ForgeChat 70B",
    description: "A conversational AI model built on Llama 3 70B, fine-tuned for multi-turn dialogue, code generation, and reasoning. OpenAI-compatible API.",
    short_description: "Llama 3 70B chat model with function calling",
    price_ada: 6.0, endpoint_url: "https://api.neuralforge.io/v1/chat/completions",
    docs_url: "https://docs.neuralforge.io", avg_latency_ms: 2100, success_rate: 99.8,
    total_jobs: 45230, uptime: 99.95, rating: 4.87, review_count: 1023,
    version: "3.0.0", model_name: "ForgeChat-70B-v3",
    example_input: '{"messages": [{"role": "user", "content": "Explain quantum computing"}]}',
    example_output: '{"choices": [{"message": {"content": "Quantum computing leverages..."}}]}',
    tags: "chat,llm,reasoning,code", status: "active",
    created_at: "2026-01-10T10:00:00Z", updated_at: "2026-07-11T10:00:00Z",
    provider_name: "NeuralForge", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Chat", category_icon: "💬",
  },
  {
    id: "s3", provider_id: "p1", category_id: "3", name: "ObjectDetect Ultra",
    description: "Real-time object detection using YOLOv9. Detects 1000+ categories with bounding boxes and segmentation masks.",
    short_description: "YOLOv9-powered real-time object detection",
    price_ada: 2.8, endpoint_url: "https://api.visionai.labs/v2/detect",
    docs_url: null, avg_latency_ms: 450, success_rate: 99.5,
    total_jobs: 28340, uptime: 99.8, rating: 4.95, review_count: 567,
    version: "1.5.0", model_name: "YOLOv9-Ultra",
    example_input: '{"image_url": "https://example.com/street.jpg"}',
    example_output: '{"detections": [{"label": "car", "confidence": 0.98}]}',
    tags: "vision,detection,yolo", status: "active",
    created_at: "2026-02-20T10:00:00Z", updated_at: "2026-07-09T10:00:00Z",
    provider_name: "VisionAI Labs", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Vision", category_icon: "👁️",
  },
  {
    id: "s4", provider_id: "p4", category_id: "4", name: "WhisperMax",
    description: "Production-ready speech-to-text powered by Whisper V3 Large. 99 languages, speaker diarization, word-level timestamps.",
    short_description: "Whisper V3 Large with speaker diarization",
    price_ada: 3.5, endpoint_url: "https://api.deepaudio.ai/v1/transcribe",
    docs_url: null, avg_latency_ms: 3200, success_rate: 98.9,
    total_jobs: 12780, uptime: 99.5, rating: 4.78, review_count: 321,
    version: "3.2.1", model_name: "Whisper-V3-Large",
    example_input: '{"audio_url": "https://example.com/meeting.mp3"}',
    example_output: '{"text": "Speaker 1: Welcome to the meeting..."}',
    tags: "speech,transcription,whisper", status: "active",
    created_at: "2026-04-05T10:00:00Z", updated_at: "2026-07-08T10:00:00Z",
    provider_name: "DeepAudio AI", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Speech-to-Text", category_icon: "🎤",
  },
  {
    id: "s5", provider_id: "p3", category_id: "5", name: "PolyGlot 200",
    description: "Neural machine translation supporting 200+ language pairs with context preservation and document-level translation.",
    short_description: "200+ language pairs with context preservation",
    price_ada: 2.2, endpoint_url: "https://api.linguatech.ai/v2/translate",
    docs_url: null, avg_latency_ms: 800, success_rate: 99.7,
    total_jobs: 67890, uptime: 99.9, rating: 4.89, review_count: 1456,
    version: "2.0.0", model_name: "PolyGlot-13B",
    example_input: '{"text": "Hello, world!", "source": "en", "target": "ja"}',
    example_output: '{"translation": "こんにちは、世界！"}',
    tags: "translation,multilingual", status: "active",
    created_at: "2025-11-15T10:00:00Z", updated_at: "2026-07-11T10:00:00Z",
    provider_name: "LinguaTech", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Translation", category_icon: "🌐",
  },
  {
    id: "s6", provider_id: "p3", category_id: "6", name: "BriefAI",
    description: "Intelligent text summarization for documents, articles, and reports. Extractive and abstractive modes.",
    short_description: "Extractive & abstractive summarization",
    price_ada: 5.0, endpoint_url: "https://api.linguatech.ai/v1/summarize",
    docs_url: null, avg_latency_ms: 1500, success_rate: 99.1,
    total_jobs: 23450, uptime: 99.7, rating: 4.72, review_count: 445,
    version: "1.3.0", model_name: "BriefAI-7B",
    example_input: '{"text": "Long article...", "max_length": 200}',
    example_output: '{"summary": "The article discusses..."}',
    tags: "summarization,text,document", status: "active",
    created_at: "2026-01-20T10:00:00Z", updated_at: "2026-07-10T10:00:00Z",
    provider_name: "LinguaTech", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Summarization", category_icon: "📝",
  },
  {
    id: "s7", provider_id: "p6", category_id: "7", name: "CodePilot Pro",
    description: "AI coding assistant supporting 30+ programming languages. Code generation, review, bug detection, and documentation.",
    short_description: "30+ language code generation and review",
    price_ada: 4.5, endpoint_url: "https://api.codeforge.ai/v2/generate",
    docs_url: null, avg_latency_ms: 1800, success_rate: 99.6,
    total_jobs: 34560, uptime: 99.8, rating: 4.91, review_count: 789,
    version: "2.5.0", model_name: "CodePilot-34B",
    example_input: '{"prompt": "Write a Python sort function", "language": "python"}',
    example_output: '{"code": "def sort_list(lst): return sorted(lst)"}',
    tags: "coding,code-generation,review", status: "active",
    created_at: "2026-02-01T10:00:00Z", updated_at: "2026-07-11T10:00:00Z",
    provider_name: "CodeForge AI", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Coding", category_icon: "💻",
  },
  {
    id: "s8", provider_id: "p5", category_id: "8", name: "DreamForge XL",
    description: "State-of-the-art image generation powered by Stable Diffusion XL. Text-to-image, image-to-image, inpainting. 4K output.",
    short_description: "SDXL-powered image generation with 4K output",
    price_ada: 5.0, endpoint_url: "https://api.pixelmind.art/v1/generate",
    docs_url: null, avg_latency_ms: 8500, success_rate: 97.8,
    total_jobs: 156780, uptime: 98.5, rating: 4.85, review_count: 2341,
    version: "2.0.0", model_name: "DreamForge-XL-v2",
    example_input: '{"prompt": "A futuristic city at sunset", "size": "1024x1024"}',
    example_output: '{"image_url": "https://cdn.pixelmind.art/gen/abc123.png"}',
    tags: "image,generation,sdxl,art", status: "active",
    created_at: "2025-12-01T10:00:00Z", updated_at: "2026-07-10T10:00:00Z",
    provider_name: "PixelMind", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Image Generation", category_icon: "🎨",
  },
  {
    id: "s9", provider_id: "p4", category_id: "10", name: "SoundSense",
    description: "Audio analysis and classification. Genre detection, emotion recognition, audio quality metrics.",
    short_description: "Audio classification and emotion detection",
    price_ada: 2.6, endpoint_url: "https://api.deepaudio.ai/v1/classify",
    docs_url: null, avg_latency_ms: 1100, success_rate: 98.5,
    total_jobs: 8920, uptime: 99.2, rating: 4.65, review_count: 178,
    version: "1.2.0", model_name: "SoundSense-L",
    example_input: '{"audio_url": "https://example.com/clip.wav"}',
    example_output: '{"genre": "jazz", "emotion": "happy"}',
    tags: "audio,classification,emotion", status: "active",
    created_at: "2026-05-10T10:00:00Z", updated_at: "2026-07-09T10:00:00Z",
    provider_name: "DeepAudio AI", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Audio", category_icon: "🔊",
  },
  {
    id: "s10", provider_id: "p2", category_id: "11", name: "DocuMind",
    description: "Intelligent document processing pipeline. OCR, NER, table extraction, and classification in one API.",
    short_description: "End-to-end intelligent document processing",
    price_ada: 4.0, endpoint_url: "https://api.neuralforge.io/v1/document",
    docs_url: null, avg_latency_ms: 4500, success_rate: 98.2,
    total_jobs: 5670, uptime: 99.0, rating: 4.73, review_count: 134,
    version: "2.0.0", model_name: "DocuMind-v2",
    example_input: '{"document_url": "https://example.com/report.pdf"}',
    example_output: '{"pages": 5, "tables": [...], "entities": [...]}',
    tags: "document,ocr,ner,table", status: "active",
    created_at: "2026-03-01T10:00:00Z", updated_at: "2026-07-08T10:00:00Z",
    provider_name: "NeuralForge", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Document AI", category_icon: "📋",
  },
  {
    id: "s11", provider_id: "p5", category_id: "9", name: "FrameAI",
    description: "Video analysis for scene detection, object tracking, action recognition, and content moderation.",
    short_description: "Scene detection and object tracking in video",
    price_ada: 6.0, endpoint_url: "https://api.pixelmind.art/v1/video/analyze",
    docs_url: null, avg_latency_ms: 12000, success_rate: 96.5,
    total_jobs: 3240, uptime: 97.5, rating: 4.58, review_count: 89,
    version: "1.0.0", model_name: "FrameAI-v1",
    example_input: '{"video_url": "https://example.com/clip.mp4"}',
    example_output: '{"duration": "02:34", "scenes": 4}',
    tags: "video,tracking,scene", status: "active",
    created_at: "2026-06-01T10:00:00Z", updated_at: "2026-07-07T10:00:00Z",
    provider_name: "PixelMind", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Video", category_icon: "🎬",
  },
  {
    id: "s12", provider_id: "p2", category_id: "1", name: "ForgeChat 8B Fast",
    description: "Lightweight conversational AI optimized for speed. Sub-500ms latency. Perfect for chatbots and support.",
    short_description: "Fast Llama 3 8B for low-latency chat",
    price_ada: 1.5, endpoint_url: "https://api.neuralforge.io/v1/chat/fast",
    docs_url: null, avg_latency_ms: 380, success_rate: 99.9,
    total_jobs: 234500, uptime: 99.99, rating: 4.76, review_count: 3456,
    version: "1.2.0", model_name: "ForgeChat-8B-Q4",
    example_input: '{"messages": [{"role": "user", "content": "What is Cardano?"}]}',
    example_output: '{"choices": [{"message": {"content": "Cardano is a PoS blockchain..."}}]}',
    tags: "chat,fast,llm,lightweight", status: "active",
    created_at: "2026-04-15T10:00:00Z", updated_at: "2026-07-12T10:00:00Z",
    provider_name: "NeuralForge", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Chat", category_icon: "💬",
  },
  {
    id: "s13", provider_id: "p7", category_id: "8", name: "Enterprise Render Farm",
    description: "Dedicated GPU clusters for ultra-high-resolution 8K video and 3D rendering. Priority queue access.",
    short_description: "8K dedicated GPU rendering cluster",
    price_ada: 500.0, endpoint_url: "https://api.renderfarm.ai/v1/job",
    docs_url: null, avg_latency_ms: 45000, success_rate: 99.9,
    total_jobs: 1205, uptime: 99.99, rating: 4.95, review_count: 85,
    version: "1.0.0", model_name: "RenderCluster-V1",
    example_input: '{"project_url": "s3://assets/proj", "resolution": "8K"}',
    example_output: '{"status": "completed", "download_url": "..."}',
    tags: "rendering,gpu,8k,video", status: "active",
    created_at: "2026-05-15T10:00:00Z", updated_at: "2026-07-12T10:00:00Z",
    provider_name: "MegaCompute", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Image Generation", category_icon: "🎨",
  },
  {
    id: "s14", provider_id: "p8", category_id: "7", name: "CodeAuditor Ultimate",
    description: "Full repository static and dynamic analysis. Detects zero-day vulnerabilities, logic bugs, and optimizes smart contracts.",
    short_description: "Enterprise smart contract and repo auditor",
    price_ada: 500.0, endpoint_url: "https://api.securecode.ai/v2/audit",
    docs_url: null, avg_latency_ms: 120000, success_rate: 99.95,
    total_jobs: 430, uptime: 100.0, rating: 4.98, review_count: 120,
    version: "4.5.0", model_name: "AuditLLM-Enterprise",
    example_input: '{"github_repo": "https://github.com/org/repo"}',
    example_output: '{"vulnerabilities": [], "score": 98}',
    tags: "audit,security,smart-contracts", status: "active",
    created_at: "2026-01-15T10:00:00Z", updated_at: "2026-07-12T10:00:00Z",
    provider_name: "SecureCode AI", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Coding", category_icon: "💻",
  },
  {
    id: "s15", provider_id: "p6", category_id: "7", name: "Neural Quantum Simulator",
    description: "Simulate complex quantum circuits using distributed AI nodes. Enterprise access.",
    short_description: "Enterprise quantum simulation",
    price_ada: 1000.0, endpoint_url: "https://api.codeforge.ai/v2/quantum",
    docs_url: null, avg_latency_ms: 250000, success_rate: 99.9,
    total_jobs: 50, uptime: 100.0, rating: 5.0, review_count: 5,
    version: "1.0.0", model_name: "QuantumSim-Pro",
    example_input: '{"circuit_url": "s3://q-circuits/test.qasm"}',
    example_output: '{"state_vector": [...]}',
    tags: "quantum,simulation,enterprise", status: "active",
    created_at: "2026-06-01T10:00:00Z", updated_at: "2026-07-12T10:00:00Z",
    provider_name: "CodeForge AI", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Coding", category_icon: "💻",
  },
  {
    id: "s16", provider_id: "p1", category_id: "3", name: "Global Weather Predictor AI",
    description: "Generate ultra-high resolution climate models and weather predictions over a 10-year period.",
    short_description: "Global high-res weather modeling",
    price_ada: 2500.0, endpoint_url: "https://api.visionai.labs/v3/climate",
    docs_url: null, avg_latency_ms: 600000, success_rate: 99.9,
    total_jobs: 10, uptime: 100.0, rating: 4.9, review_count: 3,
    version: "1.0.0", model_name: "ClimateVision-X",
    example_input: '{"region": "global", "timeline_years": 10}',
    example_output: '{"forecast_data_url": "s3://climate/result.nc"}',
    tags: "climate,weather,vision,modeling", status: "active",
    created_at: "2026-06-15T10:00:00Z", updated_at: "2026-07-12T10:00:00Z",
    provider_name: "VisionAI Labs", provider_wallet: "addr_test1qz2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3jcu5d8ps7zex2k2xt3uqxgjqnnj83ws8lhrn648jjxtwq2ytjqp",
    category_name: "Vision", category_icon: "👁️",
  }
];

export const mockProviderDashboard: ProviderDashboard = {
  total_revenue_ada: 1247.50,
  total_requests: 15230,
  total_jobs_completed: 14987,
  avg_latency_ms: 1450,
  success_rate: 98.4,
  rating: 4.88,
  active_services: 4,
  revenue_chart: [
    { date: "Jul 6", amount: 142.5 },
    { date: "Jul 7", amount: 198.3 },
    { date: "Jul 8", amount: 156.7 },
    { date: "Jul 9", amount: 203.1 },
    { date: "Jul 10", amount: 189.4 },
    { date: "Jul 11", amount: 221.8 },
    { date: "Jul 12", amount: 135.7 },
  ],
};

export const mockConsumerDashboard: ConsumerDashboard = {
  total_spent_ada: 42.75,
  total_purchases: 28,
  total_reviews: 12,
  favorite_category: "Chat",
  recent_purchases: [
    { id: "t1", service_name: "ForgeChat 70B", amount_ada: 0.3, status: "completed", date: "2026-07-12 09:15" },
    { id: "t2", service_name: "DocuScan Pro", amount_ada: 0.5, status: "completed", date: "2026-07-11 14:30" },
    { id: "t3", service_name: "PolyGlot 200", amount_ada: 0.2, status: "completed", date: "2026-07-11 11:45" },
    { id: "t4", service_name: "DreamForge XL", amount_ada: 2.0, status: "completed", date: "2026-07-10 16:20" },
    { id: "t5", service_name: "CodePilot Pro", amount_ada: 0.4, status: "completed", date: "2026-07-10 09:00" },
  ],
};

export const mockReviews: Review[] = [
  { id: "r1", service_id: "s1", consumer_id: "c1", rating: 5, comment: "Incredible OCR accuracy! Handled my handwritten notes perfectly. Best service on the platform.", created_at: "2026-07-11T14:30:00Z", consumer_name: "ada_whale" },
  { id: "r2", service_id: "s1", consumer_id: "c2", rating: 4.5, comment: "Great for invoice processing. Fast and reliable. The table extraction feature is a game-changer.", created_at: "2026-07-10T09:15:00Z", consumer_name: "crypto_dev_42" },
  { id: "r3", service_id: "s1", consumer_id: "c3", rating: 5, comment: "Using this for my document digitization startup. Handles 50+ languages as advertised. Worth every lovelace!", created_at: "2026-07-09T16:45:00Z", consumer_name: "defi_builder" },
  { id: "r4", service_id: "s1", consumer_id: "c4", rating: 4, comment: "Solid OCR service. Sometimes struggles with very low resolution images, but overall excellent.", created_at: "2026-07-08T11:20:00Z", consumer_name: "nft_collector" },
  { id: "r5", service_id: "s1", consumer_id: "c5", rating: 5, comment: "Replaced our entire OCR pipeline with this. The ADA pricing is so much more affordable than traditional APIs.", created_at: "2026-07-07T08:00:00Z", consumer_name: "stake_pool_op" },
];
